name: Anchor Program CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      SOLANA_VERSION: 1.16.0
    steps:
      - uses: actions/checkout@v3

      - name: Cache Solana Tool Suite
        uses: actions/cache@v3
        id: cache-solana
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
            ~/.solana
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc, cargo
          override: true

      - name: Install Solana Tools
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new --no-bip39-passphrase
          solana config set --url localhost
          cargo install cargo-build-bpf

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Anchor CLI
        run: |
          npm install -g @coral-xyz/anchor-cli
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest

      - name: Install Project Dependencies
        run: yarn install

      - name: Build Program
        run: |
          anchor build

      - name: Run Tests
        run: |
          anchor test