name: Anchor Program CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.16.0/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase

      - name: Install Anchor CLI
        run: |
          npm install -g @project-serum/anchor-cli
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest

      - name: Build Program
        run: anchor build

      - name: Run Rust Tests
        run: cargo test --manifest-path programs/meme_fund/Cargo.toml
        
      - name: Install Node dependencies
        run: yarn install

      - name: Run Anchor Tests
        run: anchor test