name: Anchor Program CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc, cargo
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.16.0/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase

      - name: Install Anchor CLI and Dependencies
        run: |
          npm install -g @coral-xyz/anchor-cli
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest
          npm install

      - name: Install Solana Build Tools
        run: |
          cargo install cargo-build-sbf
          cargo build-sbf --version

      - name: Build Program
        run: anchor build

      - name: Run Tests
        run: |
          solana config set --url localhost
          anchor test