name: Anchor Program CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLANA_CLI_VERSION: 1.16.0
  NODE_VERSION: 18

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc, cargo
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          source $HOME/.cargo/env
          echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV
          solana --version
          solana-keygen new --no-bip39-passphrase

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Anchor Dependencies
        run: |
          npm install -g @coral-xyz/anchor-cli
          npm install -g yarn
          yarn install

      - name: Build and Test
        run: |
          echo $PATH
          solana --version
          solana config set --url localhost
          anchor --version
          anchor build
          anchor test