name: Anchor Program CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies and Run Tests
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
          sh -c "$(curl -sSfL https://release.solana.com/v1.16.0/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g @coral-xyz/anchor-cli
          npm install -g yarn
          yarn install
          solana-keygen new --no-bip39-passphrase
          anchor build
          anchor test