name: Anchor Program CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.0'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.23/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase
          solana config set --url devnet
          solana-keygen new --no-bip39-passphrase -o /home/runner/.config/solana/devnet.json
          solana config set --keypair /home/runner/.config/solana/devnet.json
          # Airdrop
          for i in {1..5}; do
            solana airdrop 2 || true
            sleep 2
          done
          solana balance

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
          npm install -g @coral-xyz/anchor-cli
          yarn install

      - name: Build and Test
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build
          # Test
          solana-test-validator &
          sleep 5
          anchor test